ProjetoSocial/Controllers/AnimaisController.cs
using System.Net;
using System.Web.Mvc;
using ProjetoSocial.Models;
using ProjetoSocial.Repository.Animal;

namespace ProjetoSocial.Controllers
{
    [Authorize]
    public class AnimaisController : Controller
    {
        private ProjetoSocialEntities db = new ProjetoSocialEntities();
        private AnimalRepository repository;

        public ActionResult Index()
        {
            NewRepository();
            return View(repository.GetAnimals());
        }
        
        public ActionResult Details(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Animal animal = repository.GetAnimalByID(id);
            if (animal == null)
                return HttpNotFound();

            return View(animal);
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            ViewBag.Vacinas = new SelectList(db.Vacinacao, "Id", "Nome");
            return View();
        }

        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Especie,Nome,Peso,Cor,Idade,DataInclusao,DataAdocao,DescricaoLocalEncontrado,Status,Informacoes,Vacinas")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.InsertAnimal(animal);
                return RedirectToAction("Index");
            }

            ViewBag.Vacinas = new SelectList(db.Vacinacao, "Id", "Nome", animal.Vacinas);
            return View(animal);
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Animal animal = repository.GetAnimalByID(id);
            if (animal == null)
                return HttpNotFound();

            ViewBag.Vacinas = new SelectList(db.Vacinacao, "Id", "Nome", animal.Vacinas);
            return View(animal);
        }

        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Especie,Nome,Peso,Cor,Idade,DataInclusao,DataAdocao,DescricaoLocalEncontrado,Status,Informacoes,Vacinas")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.UpdateAnimal(animal);
                return RedirectToAction("Index");
            }

            ViewBag.Vacinas = new SelectList(db.Vacinacao, "Id", "Nome", animal.Vacinas);
            return View(animal);
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Animal animal = repository.GetAnimalByID(id);
            if (animal == null)
                return HttpNotFound();

            return View(animal);
        }

        [Authorize(Roles = "Administrador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NewRepository();
            Animal animal = repository.GetAnimalByID(id);

            repository.DeleteAnimal(animal.Id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }

        private void NewRepository()
        {
            repository = new AnimalRepository(db);
        }
    }
}

ProjetoSocial/Controllers/ContatosController.cs
using System.Net;
using System.Web.Mvc;
using ProjetoSocial.Models;
using ProjetoSocial.Repository.Contato;

namespace ProjetoSocial.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ContatosController : Controller
    {
        private ProjetoSocialEntities db = new ProjetoSocialEntities();
        private ContatoRepository repository;

        public ActionResult Index()
        {
            NewRepository();
            return View(repository.GetContatos());
        }

        public ActionResult Details(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Contato contato = repository.GetContatoByID(id);
            if (contato == null)
                return HttpNotFound();

            return View(contato);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Telefone,Celular,Email,Informacoes")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.InsertContato(contato);
                return RedirectToAction("Index");
            }

            return View(contato);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Contato contato = repository.GetContatoByID(id);
            if (contato == null)
                return HttpNotFound();

            return View(contato);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Telefone,Celular,Email,Informacoes")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.UpdateContato(contato);
                return RedirectToAction("Index");
            }
            return View(contato);
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Contato contato = repository.GetContatoByID(id);
            if (contato == null)
                return HttpNotFound();

            return View(contato);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NewRepository();
            Contato contato = repository.GetContatoByID(id);

            repository.DeleteContato(contato.Id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void NewRepository()
        {
            repository = new ContatoRepository(db);
        }
    }
}

ProjetoSocial/Controllers/EnderecosController.cs
using System.Net;
using System.Web.Mvc;
using ProjetoSocial.Models;
using ProjetoSocial.Repository.Endereco;

namespace ProjetoSocial.Controllers
{
    [Authorize]
    public class EnderecosController : Controller
    {
        private ProjetoSocialEntities db = new ProjetoSocialEntities();
        private EnderecoRepository repository;

        public ActionResult Index()
        {
            NewRepository();
            return View(repository.GetEnderecos());
        }
        
        public ActionResult Details(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Endereco endereco = repository.GetEnderecoByID(id);
            if (endereco == null)
                return HttpNotFound();

            return View(endereco);
        }
        
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Logradouro,Numero,Bairro,Complemento,Cep,Municipio,Uf,Informacoes")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.InsertEndereco(endereco);
                return RedirectToAction("Index");
            }

            return View(endereco);
        }
        
        public ActionResult Edit(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Endereco endereco = repository.GetEnderecoByID(id);
            if (endereco == null)
                return HttpNotFound();

            return View(endereco);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Logradouro,Numero,Bairro,Complemento,Cep,Municipio,Uf,Informacoes")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.UpdateEndereco(endereco);
                return RedirectToAction("Index");
            }
            return View(endereco);
        }
        
        public ActionResult Delete(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Endereco endereco = repository.GetEnderecoByID(id);
            if (endereco == null)
                return HttpNotFound();

            return View(endereco);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NewRepository();
            Endereco endereco = repository.GetEnderecoByID(id);
            repository.DeleteEndereco(endereco.Id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void NewRepository()
        {
            repository = new EnderecoRepository(db);
        }
    }
}

ProjetoSocial/Controllers/PessoasController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ProjetoSocial.Models;
using ProjetoSocial.Repository.Pessoa;

namespace ProjetoSocial.Controllers
{
    [Authorize]
    public class PessoasController : Controller
    {
        private ProjetoSocialEntities db = new ProjetoSocialEntities();
        private PessoaRepository repository;

        public ActionResult Index()
        {
            NewRepository();
            var pessoa = repository.GetPessoas();
            return View(pessoa.ToList());
        }

        public ActionResult Details(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Pessoa pessoa = repository.GetPessoaByID(id);
            if (pessoa == null)
                return HttpNotFound();
            return View(pessoa);
        }

        public ActionResult Create()
        {
            ViewBag.AnimaisAdotados = new SelectList(db.Animal, "Id", "Especie");
            ViewBag.Contato = new SelectList(db.Contato, "Id", "Telefone");
            ViewBag.Endereco = new SelectList(db.Endereco, "Id", "Logradouro");
            ViewBag.Login = new SelectList(db.Login, "Id", "Usuario");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,DataInclusao,Informacoes,Endereco,Contato,Login,AnimaisAdotados")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.InsertPessoa(pessoa);
                return RedirectToAction("Index");
            }

            ViewBag.AnimaisAdotados = new SelectList(db.Animal, "Id", "Especie", pessoa.AnimaisAdotados);
            ViewBag.Contato = new SelectList(db.Contato, "Id", "Telefone", pessoa.Contato);
            ViewBag.Endereco = new SelectList(db.Endereco, "Id", "Logradouro", pessoa.Endereco);
            ViewBag.Login = new SelectList(db.Login, "Id", "Usuario", pessoa.Login);
            return View(pessoa);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Pessoa pessoa = repository.GetPessoaByID(id);
            if (pessoa == null)
                return HttpNotFound();

            ViewBag.AnimaisAdotados = new SelectList(db.Animal, "Id", "Especie", pessoa.AnimaisAdotados);
            ViewBag.Contato = new SelectList(db.Contato, "Id", "Telefone", pessoa.Contato);
            ViewBag.Endereco = new SelectList(db.Endereco, "Id", "Logradouro", pessoa.Endereco);
            ViewBag.Login = new SelectList(db.Login, "Id", "Usuario", pessoa.Login);
            return View(pessoa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,DataInclusao,Informacoes,Endereco,Contato,Login,AnimaisAdotados")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.UpdatePessoa(pessoa);
                return RedirectToAction("Index");
            }
            ViewBag.AnimaisAdotados = new SelectList(db.Animal, "Id", "Especie", pessoa.AnimaisAdotados);
            ViewBag.Contato = new SelectList(db.Contato, "Id", "Telefone", pessoa.Contato);
            ViewBag.Endereco = new SelectList(db.Endereco, "Id", "Logradouro", pessoa.Endereco);
            ViewBag.Login = new SelectList(db.Login, "Id", "Usuario", pessoa.Login);
            return View(pessoa);
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Pessoa pessoa = repository.GetPessoaByID(id);
            if (pessoa == null)
                return HttpNotFound();
            return View(pessoa);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NewRepository();
            Pessoa pessoa = repository.GetPessoaByID(id);
            repository.DeletePessoa(pessoa.Id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }

        private void NewRepository()
        {
            repository = new PessoaRepository(db);
        }
    }
}

ProjetoSocial/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjetoSocial/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Portal gerenciador de animais para adoção">
    <meta name="author" content="Luiz Renato">

    <title>SGA | Adoção de animais</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/album.css" rel="stylesheet">
</head>

<body>
    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">O que fazemos</h4>
                        <p class="text-muted">Fazemos um trabalho social que visa a adoção de animais que por algum motivo foram abandonados e que, infelizmente se encontram sem um lar.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Menu</h4>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Animais</a></li>
                            <li>@Html.ActionLink("Cadastro", "Login", "Home")</li>
                            <li>@Html.ActionLink("Login", "Login", "Home")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex justify-content-between">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
                    <strong>Adoção de animais</strong>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>

    @RenderBody()

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">Topo</a>
            </p>
            <p>Desenvolvido por Luiz Renato Sebastião | Setembro/2018</p>
            <p>Conheça minhas competências no <a href="https://www.linkedin.com/in/luiz-renato-003aaa7a/">linkedin</a> .</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="~/Scripts/popper.js"></script>
    <script src="~/dist/bootstrap.min.js"></script>
    <script src="~/Scripts/holder.min.js"></script>
</body>
</html>

ProjetoSocial/Views/Shared/_LayoutAdm.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>SGA | Controle de animais</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/dashboard.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">SGA | Controle de animais</a>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Procurar" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="@Url.Action("Signout", "PainelAdministrativo")">Logoff</a>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="@Url.Action("Index", "PainelAdministrativo")">
                                <span data-feather="home"></span>
                                Home <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Animais")">
                                <span data-feather="file"></span>
                                Animais
                            </a>
                        </li>
                        @if (this.User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Pessoas")">
                                    <span data-feather="shopping-cart"></span>
                                    Pessoas
                                </a>
                            </li>
                        }
                        @if (this.User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Contatos")">
                                    <span data-feather="users"></span>
                                    Contatos
                                </a>
                            </li>
                        }
                        @if (this.User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Enderecos")">
                                    <span data-feather="bar-chart-2"></span>
                                    Endereços
                                </a>
                            </li>
                        }
                        @if (this.User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Vacinacoes")">
                                    <span data-feather="layers"></span>
                                    Vacinações
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                @RenderBody()
            </main>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="~/Scripts/jquery-slim.min.js"><\/script>')</script>
    <script src="~/Scripts/popper.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
        feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
                datasets: [{
                    data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#007bff',
                    borderWidth: 4,
                    pointBackgroundColor: '#007bff'
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: false
                        }
                    }]
                },
                legend: {
                    display: false,
                }
            }
        });
    </script>
</body>
</html>

ProjetoSocial/Views/Shared/_LayoutCadastro.cshtml
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SGA | Cadastro de usuário</title>
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
</head>

<body class="bg-light">

    <div class="container">
        @RenderBody()
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="~/Scripts/popper.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
</body>
</html>

ProjetoSocial/Views/Shared/_LayoutLogin.cshtml
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SGA | Adoção de animais</title>
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/signin.css" rel="stylesheet">
</head>

<body class="text-center">

    @RenderBody()

</body>
</html>