ProjetoSocial/Models/Login.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.Pessoa = new HashSet<Pessoa>();
        }
    
        public string Id { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string Status { get; set; }
        public string Informacoes { get; set; }
        public string Perfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}

ProjetoSocial/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Web.Security;
using ProjetoSocial.Models;
using ProjetoSocial.Repository.Login;

namespace ProjetoSocial.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }

        public ActionResult Login()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }

        [HttpPost]
        public ActionResult Login(string usuario, string senha)
        {
            ProjetoSocialEntities objempcontext = new ProjetoSocialEntities();
            LoginRepository log = new LoginRepository(objempcontext);
            var vLogin = log.GetLoginByUserPass(usuario, senha);

            if (vLogin != null)
            {
                FormsAuthentication.SetAuthCookie(vLogin.Usuario, false);
                Session["Nome"] = vLogin.Usuario;
                Session["Status"] = vLogin.Status;
                return RedirectToAction("Index", "PainelAdministrativo");
            }
            else
            {
                ModelState.Clear();
                ViewData["MensagemLogin"] = "Usuário / Senha inválidos";
                return View(new Login());
            }
        }

        public ActionResult Cadastro()
        {
            ViewBag.Message = "Cadastro de usuários.";
            return View();
        }
    }
}

ProjetoSocial/Controllers/LoginsController.cs
using System.Net;
using System.Web.Mvc;
using ProjetoSocial.Models;
using ProjetoSocial.Repository.Login;

namespace ProjetoSocial.Controllers
{
    
    public class LoginsController : Controller
    {
        private ProjetoSocialEntities db = new ProjetoSocialEntities();
        private LoginRepository repository = null;

        [Authorize]
        public ActionResult Index()
        {
            repository = new LoginRepository(db);
            return View(repository.GetLogins());
        }

        [Authorize]
        public ActionResult Details(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Login login = repository.GetLoginByID(id);
            if (login == null)
                return HttpNotFound();

            return View(login);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Usuario,Senha,Status,Informacoes")] Login login)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.InsertLogin(login);
                return RedirectToAction("Index");
            }

            return View(login);
        }

        [Authorize]
        public ActionResult Edit(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Login login = repository.GetLoginByID(id);
            if (login == null)
                return HttpNotFound();
            return View(login);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Usuario,Senha,Status,Informacoes")] Login login)
        {
            if (ModelState.IsValid)
            {
                NewRepository();
                repository.UpdateLogin(login);
                return RedirectToAction("Index");
            }
            return View(login);
        }

        [Authorize]
        public ActionResult Delete(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            NewRepository();
            Login login = repository.GetLoginByID(id);
            if (login == null)
                return HttpNotFound();

            return View(login);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NewRepository();
            Login login = repository.GetLoginByID(id);
            repository.DeleteLogin(login.Id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }

        private void NewRepository()
        {
            repository = new LoginRepository(db);
        }
    }
}

ProjetoSocial/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<link href="signin.css" rel="stylesheet">
<form class="form-signin">
    <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
</form>

ProjetoSocial/Views/Home/Cadastro.cshtml
@model ProjetoSocial.Models.Login

@{
    ViewBag.Title = "Cadastro";
    Layout = "~/Views/Shared/_LayoutCadastro.cshtml";
}

<div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h2>Formulário de cadastro</h2>
    <p class="lead">Conclua seu cadastro para poder ver todos animais disponíveis para adoção.</p>
</div>

<div class="row">
    
    @using (Html.BeginForm("Create", "Logins", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-12 order-md-1">
        <h4 class="mb-3">Preencha todos os campos</h4>
        <form class="needs-validation" novalidate>
            <div class="mb-3">
                <label for="username">Usuário</label>
                <div class="input-group">
                    @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                    <div class="invalid-feedback" style="width: 100%;">
                        Insira o nome de usuario
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <label for="email">Senha </label>
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger", type = "password" })
                <div class="invalid-feedback">
                    Insira a senha
                </div>
            </div>
            <hr class="mb-4">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="same-address">
                <label class="custom-control-label" for="same-address">Estou ciente do cadastro no site</label>
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="save-info">
                <label class="custom-control-label" for="save-info">Aceito os termos do site</label>
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Salvar</button>
        </form>
    </div>
}
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2018 SGA</p>
    <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Privacidade</a></li>
        <li class="list-inline-item"><a href="#">Termos</a></li>
        <li class="list-inline-item"><a href="#">Suporte</a></li>
    </ul>
</footer>

ProjetoSocial/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjetoSocial/Views/Home/Login.cshtml
@model ProjetoSocial.Models.Login

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}


@using (Html.BeginForm("Login", "Home", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-signin" }))
{
    @Html.AntiForgeryToken()
    <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Faça seu login</h1>
    @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control input-lg", placeholder = "Usuário", autofocus = true } })
    @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
    
    @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control input-lg", placeholder = "Senha", type = "password", autofocus = true } })
    @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })

    <div>@ViewData["MensagemLogin"]</div>

    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Lembrar-me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Acessar</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2018</p>
}